### ISSUE TITLE
.steps vs. .js files

### ISSUE THREAD

**Issue by bkruggel** [canvaspixels/courgette#53]
We've been using Courgette for a while now and are now at the point where we want to refactor our tests to have short complicated tests in the .feature files (these should be readable by any person in the organization), simple and reusable step definitions in the .steps file (those should be readable by the developers and QA) and then the common-step-definitions.js should only be read and written by the developers.

We realized that it does not work this way, since loadSteps.js is only including the predefined JavaScript steps, not those that we have written internally (we use them to sort tables, randomize input and iterate over fields).

What is your stance on this? How would you use Courgette to achieve a three-layered approach as I have outlined above?

**Comment by canvaspixels** [comment]
Apologies for not getting back to you sooner. There's no reason why this couldn't be achieved by bringing loadSteps into your project. You'd have to define your steps in a similar way to how the commonGivenSteps.js steps are defined for example though. There should be a way to get all the steps defined and extract them in a similar format, I haven't invested any time into it though. 

I'm currently working on a recorder for it to create some quick and dirty tests that you'll be able to DRY out and start to maintain. The website is still under construction too. Glad to hear you're using it. Please submit a PR if you manage to come up with a solution, otherwise i'll get round to it at some point, but isn't a priority.

**Comment by canvaspixels** [comment]
This has been added in https://github.com/canvaspixels/courgette/pull/62

Fixed in courgette@2.20.0
